export interface IdxTickerItem {
  ticker: string;
  name: string;
  sector: string;
}

export const IDX_UNIVERSE: IdxTickerItem[] = [
  // ─── 1. FINANCIALS (110 Emiten) ───
  { ticker: "ABDA", name: "Asuransi Bina Dana Arta Tbk", sector: "Financials" },
  { ticker: "ADMF", name: "Adira Dinamika Multi Finance Tbk", sector: "Financials" },
  { ticker: "AGRO", name: "Bank Raya Indonesia Tbk", sector: "Financials" },
  { ticker: "AHAP", name: "Asuransi Harta Aman Pratama Tbk", sector: "Financials" },
  { ticker: "AMAG", name: "Asuransi Multi Artha Guna Tbk", sector: "Financials" },
  { ticker: "AMAR", name: "Bank Amar Indonesia Tbk", sector: "Financials" },
  { ticker: "AMOR", name: "Ashmore Asset Management Indonesia Tbk", sector: "Financials" },
  { ticker: "APIC", name: "Pacific Strategic Financial Tbk", sector: "Financials" },
  { ticker: "ARTO", name: "Bank Jago Tbk", sector: "Financials" },
  { ticker: "ASBI", name: "Asuransi Bintang Tbk", sector: "Financials" },
  { ticker: "ASDF", name: "Astra Sedaya Finance Tbk", sector: "Financials" },
  { ticker: "ASIA", name: "Asuransi Kresna Mitra Tbk", sector: "Financials" },
  { ticker: "ASJT", name: "Asuransi Jasa Tania Tbk", sector: "Financials" },
  { ticker: "ASMI", name: "Asuransi Kresna Mitra Tbk", sector: "Financials" },
  { ticker: "ASRM", name: "Asuransi Ramayana Tbk", sector: "Financials" },
  { ticker: "BABP", name: "Bank MNC Internasional Tbk", sector: "Financials" },
  { ticker: "BABX", name: "Bank MNC Internasional Tbk", sector: "Financials" },
  { ticker: "BACA", name: "Bank Capital Indonesia Tbk", sector: "Financials" },
  { ticker: "BBCA", name: "Bank Central Asia Tbk", sector: "Financials" },
  { ticker: "BBHI", name: "Allo Bank Indonesia Tbk", sector: "Financials" },
  { ticker: "BBKP", name: "KB Bank Tbk", sector: "Financials" },
  { ticker: "BBLD", name: "Buana Finance Tbk", sector: "Financials" },
  { ticker: "BBNI", name: "Bank Negara Indonesia (Persero) Tbk", sector: "Financials" },
  { ticker: "BBRI", name: "Bank Rakyat Indonesia (Persero) Tbk", sector: "Financials" },
  { ticker: "BBSI", name: "Krom Bank Indonesia Tbk", sector: "Financials" },
  { ticker: "BBTN", name: "Bank Tabungan Negara (Persero) Tbk", sector: "Financials" },
  { ticker: "BBYB", name: "Bank Neo Commerce Tbk", sector: "Financials" },
  { ticker: "BCAP", name: "MNC Kapital Indonesia Tbk", sector: "Financials" },
  { ticker: "BCIC", name: "Bank JTrust Indonesia Tbk", sector: "Financials" },
  { ticker: "BDMN", name: "Bank Danamon Indonesia Tbk", sector: "Financials" },
  { ticker: "BEKS", name: "Bank Pembangunan Daerah Banten Tbk", sector: "Financials" },
  { ticker: "BFIN", name: "BFI Finance Indonesia Tbk", sector: "Financials" },
  { ticker: "BGTG", name: "Bank Ganesha Tbk", sector: "Financials" },
  { ticker: "BGTN", name: "Bank Ganesha Tbk", sector: "Financials" },
  { ticker: "BHAT", name: "Bhakti Multi Artha Tbk", sector: "Financials" },
  { ticker: "BHIT", name: "MNC Asia Holding Tbk", sector: "Financials" },
  { ticker: "BINA", name: "Bank Ina Perdana Tbk", sector: "Financials" },
  { ticker: "BJBR", name: "Bank Pembangunan Daerah Jawa Barat dan Banten Tbk", sector: "Financials" },
  { ticker: "BJTM", name: "Bank Pembangunan Daerah Jawa Timur Tbk", sector: "Financials" },
  { ticker: "BKSW", name: "Bank QNB Indonesia Tbk", sector: "Financials" },
  { ticker: "BMAS", name: "Bank Maspion Indonesia Tbk", sector: "Financials" },
  { ticker: "BMRI", name: "Bank Mandiri (Persero) Tbk", sector: "Financials" },
  { ticker: "BNBA", name: "Bank Bumi Arta Tbk", sector: "Financials" },
  { ticker: "BNGA", name: "Bank CIMB Niaga Tbk", sector: "Financials" },
  { ticker: "BNII", name: "Bank Maybank Indonesia Tbk", sector: "Financials" },
  { ticker: "BNLI", name: "Bank Permata Tbk", sector: "Financials" },
  { ticker: "BOLA", name: "Bali Bintang Sejahtera Tbk", sector: "Financials" },
  { ticker: "BPFI", name: "Batavia Prosperindo Finance Tbk", sector: "Financials" },
  { ticker: "BPII", name: "Batavia Prosperindo Internasional Tbk", sector: "Financials" },
  { ticker: "BPTR", name: "Batavia Prosperindo Trans Tbk", sector: "Financials" },
  { ticker: "BRIS", name: "Bank Syariah Indonesia Tbk", sector: "Financials" },
  { ticker: "BSIM", name: "Bank Sinarmas Tbk", sector: "Financials" },
  { ticker: "BSWD", name: "Bank of India Indonesia Tbk", sector: "Financials" },
  { ticker: "BTPN", name: "Bank SMBC Indonesia Tbk", sector: "Financials" },
  { ticker: "BTPS", name: "Bank BTPN Syariah Tbk", sector: "Financials" },
  { ticker: "BVIC", name: "Bank Victoria International Tbk", sector: "Financials" },
  { ticker: "CASA", name: "Capital Financial Indonesia Tbk", sector: "Financials" },
  { ticker: "CFIN", name: "Clipan Finance Indonesia Tbk", sector: "Financials" },
  { ticker: "DEFI", name: "Danasupra Erapacific Tbk", sector: "Financials" },
  { ticker: "DNAR", name: "Bank Oke Indonesia Tbk", sector: "Financials" },
  { ticker: "FINA", name: "Finansia Multi Finance Tbk", sector: "Financials" },
  { ticker: "FUJI", name: "Fuji Finance Indonesia Tbk", sector: "Financials" },
  { ticker: "FUTR", name: "Futura Energi Global Tbk", sector: "Financials" },
  { ticker: "HAJI", name: "Haji Investama Tbk", sector: "Financials" },
  { ticker: "HARO", name: "Harmoni Sejahtera Tbk", sector: "Financials" },
  { ticker: "HDFA", name: "Radana Bhaskara Finance Tbk", sector: "Financials" },
  { ticker: "INCF", name: "Indo Komoditi Korpora Tbk", sector: "Financials" },
  { ticker: "INPC", name: "Bank Artha Graha Internasional Tbk", sector: "Financials" },
  { ticker: "JMAS", name: "Asuransi Jiwa Syariah Jasa Mitra Abadi Tbk", sector: "Financials" },
  { ticker: "KREN", name: "Kresna Graha Investama Tbk", sector: "Financials" },
  { ticker: "LIFE", name: "Asuransi Jiwa Sinarmas MSIG Tbk", sector: "Financials" },
  { ticker: "LPGI", name: "Lippo General Insurance Tbk", sector: "Financials" },
  { ticker: "LPLI", name: "Star Pacific Tbk", sector: "Financials" },
  { ticker: "LPPS", name: "Lippo Securities Tbk", sector: "Financials" },
  { ticker: "MASB", name: "Bank Multiarta Sentosa Tbk", sector: "Financials" },
  { ticker: "MAYA", name: "Bank Mayapada Internasional Tbk", sector: "Financials" },
  { ticker: "MCOR", name: "Bank China Construction Bank Indonesia Tbk", sector: "Financials" },
  { ticker: "MEGA", name: "Bank Mega Tbk", sector: "Financials" },
  { ticker: "MFIN", name: "Mandala Multifinance Tbk", sector: "Financials" },
  { ticker: "MREI", name: "Maskapai Reasuransi Indonesia Tbk", sector: "Financials" },
  { ticker: "MTWI", name: "Malacca Trust Wuwungan Insurance Tbk", sector: "Financials" },
  { ticker: "NICK", name: "Charnic Capital Tbk", sector: "Financials" },
  { ticker: "NISP", name: "Bank OCBC NISP Tbk", sector: "Financials" },
  { ticker: "NOBU", name: "Bank Nationalnobu Tbk", sector: "Financials" },
  { ticker: "OCAP", name: "Onix Capital Tbk", sector: "Financials" },
  { ticker: "PADI", name: "Minna Padi Investama Sekuritas Tbk", sector: "Financials" },
  { ticker: "PANS", name: "Panin Sekuritas Tbk", sector: "Financials" },
  { ticker: "PEGE", name: "Panca Global Kapital Tbk", sector: "Financials" },
  { ticker: "PLAS", name: "Polaris Investama Tbk", sector: "Financials" },
  { ticker: "PNBN", name: "Bank Pan Indonesia Tbk", sector: "Financials" },
  { ticker: "PNBS", name: "Bank Panin Dubai Syariah Tbk", sector: "Financials" },
  { ticker: "PNIN", name: "Paninvest Tbk", sector: "Financials" },
  { ticker: "PNLF", name: "Panin Financial Tbk", sector: "Financials" },
  { ticker: "POLA", name: "Pool Advista Finance Tbk", sector: "Financials" },
  { ticker: "POOL", name: "Pool Advista Indonesia Tbk", sector: "Financials" },
  { ticker: "RELI", name: "Reliance Sekuritas Indonesia Tbk", sector: "Financials" },
  { ticker: "SDRA", name: "Bank Woori Saudara Indonesia 1906 Tbk", sector: "Financials" },
  { ticker: "SMMA", name: "Sinarmas Multiartha Tbk", sector: "Financials" },
  { ticker: "SRTG", name: "Saratoga Investama Sedaya Tbk", sector: "Financials" },
  { ticker: "TIFA", name: "KDB Tifa Finance Tbk", sector: "Financials" },
  { ticker: "TRIM", name: "Trimegah Sekuritas Indonesia Tbk", sector: "Financials" },
  { ticker: "TRUS", name: "Trust Finance Indonesia Tbk", sector: "Financials" },
  { ticker: "TUGU", name: "Asuransi Tugu Pratama Indonesia Tbk", sector: "Financials" },
  { ticker: "VALU", name: "Value Creation Indonesia Tbk", sector: "Financials" },
  { ticker: "VICO", name: "Victoria Investama Tbk", sector: "Financials" },
  { ticker: "VINS", name: "Victoria Insurance Tbk", sector: "Financials" },
  { ticker: "VRNA", name: "Mizuho Leasing Indonesia Tbk", sector: "Financials" },
  { ticker: "VTNY", name: "Venteny Fortuna International Tbk", sector: "Financials" },
  { ticker: "WOMF", name: "Wahana Ottomitra Multiartha Tbk", sector: "Financials" },
  { ticker: "YULE", name: "Yulie Sekuritas Indonesia Tbk", sector: "Financials" },

  // ─── 2. ENERGY (84 Emiten) ───
  { ticker: "ABMM", name: "ABM Investama Tbk", sector: "Energy" },
  { ticker: "ADRO", name: "Adaro Energy Indonesia Tbk", sector: "Energy" },
  { ticker: "AIMS", name: "Akbar Indo Makmur Stimec Tbk", sector: "Energy" },
  { ticker: "AKRA", name: "AKR Corporindo Tbk", sector: "Energy" },
  { ticker: "ALII", name: "Ancara Logistics Indonesia Tbk", sector: "Energy" },
  { ticker: "APEX", name: "Apexindo Pratama Duta Tbk", sector: "Energy" },
  { ticker: "ARII", name: "Atlas Resources Tbk", sector: "Energy" },
  { ticker: "ARTI", name: "Ratu Prabu Energi Tbk", sector: "Energy" },
  { ticker: "ATLA", name: "Atlantis Subsea Indonesia Tbk", sector: "Energy" },
  { ticker: "BAIK", name: "Adhi Kartiko Pratama Tbk", sector: "Energy" },
  { ticker: "BESS", name: "Batulicin Nusantara Maritim Tbk", sector: "Energy" },
  { ticker: "BIAT", name: "Batulicin Nusantara Maritim Tbk", sector: "Energy" },
  { ticker: "BIPI", name: "Astrindo Nusantara Infrastruktur Tbk", sector: "Energy" },
  { ticker: "BOSS", name: "Borneo Olah Sarana Sukses Tbk", sector: "Energy" },
  { ticker: "BSML", name: "Bintang Samudera Mandiri Lines Tbk", sector: "Energy" },
  { ticker: "BSSR", name: "Baramulti Suksessarana Tbk", sector: "Energy" },
  { ticker: "BUMI", name: "Bumi Resources Tbk", sector: "Energy" },
  { ticker: "BYAN", name: "Bayan Resources Tbk", sector: "Energy" },
  { ticker: "CANO", name: "Caniago Resources Tbk", sector: "Energy" },
  { ticker: "CBRE", name: "Cakra Buana Resources Energi Tbk", sector: "Energy" },
  { ticker: "CGAS", name: "Citra Nusantara Gemilang Tbk", sector: "Energy" },
  { ticker: "CNKO", name: "Exploitasi Energi Indonesia Tbk", sector: "Energy" },
  { ticker: "COAL", name: "Black Diamond Resources Tbk", sector: "Energy" },
  { ticker: "CUAN", name: "Petrindo Jaya Kreasi Tbk", sector: "Energy" },
  { ticker: "DEWA", name: "Darma Henwa Tbk", sector: "Energy" },
  { ticker: "DOID", name: "Delta Dunia Makmur Tbk", sector: "Energy" },
  { ticker: "DSSA", name: "Dian Swastatika Sentosa Tbk", sector: "Energy" },
  { ticker: "DWGL", name: "Dwi Guna Laksana Tbk", sector: "Energy" },
  { ticker: "ELSA", name: "Elnusa Tbk", sector: "Energy" },
  { ticker: "ENRG", name: "Energi Mega Persada Tbk", sector: "Energy" },
  { ticker: "FIRE", name: "Alfa Energi Investama Tbk", sector: "Energy" },
  { ticker: "GEMS", name: "Golden Energy Mines Tbk", sector: "Energy" },
  { ticker: "GGRP", name: "Gunung Raja Paksi Tbk", sector: "Energy" },
  { ticker: "GTBO", name: "Garda Tujuh Buana Tbk", sector: "Energy" },
  { ticker: "HADE", name: "Humpuss Alami Tbk", sector: "Energy" },
  { ticker: "HIDA", name: "Humpuss Intermoda Transportasi Tbk", sector: "Energy" },
  { ticker: "HILL", name: "Hillcon Tbk", sector: "Energy" },
  { ticker: "HRUM", name: "Harum Energy Tbk", sector: "Energy" },
  { ticker: "IATA", name: "MNC Energy Investments Tbk", sector: "Energy" },
  { ticker: "INDY", name: "Indika Energy Tbk", sector: "Energy" },
  { ticker: "INPS", name: "Indah Prakasa Sentosa Tbk", sector: "Energy" },
  { ticker: "ITMA", name: "Sumber Energi Andalan Tbk", sector: "Energy" },
  { ticker: "ITMG", name: "Indo Tambangraya Megah Tbk", sector: "Energy" },
  { ticker: "KKGI", name: "Resource Alam Indonesia Tbk", sector: "Energy" },
  { ticker: "KOPI", name: "Mitra Energi Persada Tbk", sector: "Energy" },
  { ticker: "LAPD", name: "Leyand International Tbk", sector: "Energy" },
  { ticker: "LEAD", name: "Logindo Samudramakmur Tbk", sector: "Energy" },
  { ticker: "MAHA", name: "Mandiri Herindo Adiperkasa Tbk", sector: "Energy" },
  { ticker: "MBAP", name: "Mitrabara Adiperdana Tbk", sector: "Energy" },
  { ticker: "MBSS", name: "Mitra Bahtera Segara Sejati Tbk", sector: "Energy" },
  { ticker: "MCOL", name: "Prima Andalan Mandiri Tbk", sector: "Energy" },
  { ticker: "MEDC", name: "Medco Energi Internasional Tbk", sector: "Energy" },
  { ticker: "MITI", name: "Mitra Investindo Tbk", sector: "Energy" },
  { ticker: "MOCI", name: "Mulia Boga Corporindo Tbk", sector: "Energy" },
  { ticker: "MSTI", name: "Mastersystem Infotama Tbk", sector: "Energy" },
  { ticker: "MTFN", name: "Capitalinc Investment Tbk", sector: "Energy" },
  { ticker: "MYOH", name: "Samindo Resources Tbk", sector: "Energy" },
  { ticker: "PGAS", name: "Perusahaan Gas Negara Tbk", sector: "Energy" },
  { ticker: "PKPK", name: "Perdana Karya Perkasa Tbk", sector: "Energy" },
  { ticker: "PTBA", name: "Bukit Asam Tbk", sector: "Energy" },
  { ticker: "PTIS", name: "Pranata Tirta Sejahtera Tbk", sector: "Energy" },
  { ticker: "PTNZ", name: "Penta Natural Resources Tbk", sector: "Energy" },
  { ticker: "PTRO", name: "Petrosea Tbk", sector: "Energy" },
  { ticker: "RAJA", name: "Rukun Raharja Tbk", sector: "Energy" },
  { ticker: "RCCC", name: "Radiant Cahaya Cemerlang Tbk", sector: "Energy" },
  { ticker: "RGAS", name: "Kian Santang Muliatama Tbk", sector: "Energy" },
  { ticker: "RIGS", name: "Rig Tenders Indonesia Tbk", sector: "Energy" },
  { ticker: "RMKE", name: "RMK Energy Tbk", sector: "Energy" },
  { ticker: "RMKO", name: "Royaltama Mulia Kontraktorindo Tbk", sector: "Energy" },
  { ticker: "RUIS", name: "Radiant Utama Interinsco Tbk", sector: "Energy" },
  { ticker: "SEMA", name: "Semacom Integrated Tbk", sector: "Energy" },
  { ticker: "SGER", name: "Sumber Global Energy Tbk", sector: "Energy" },
  { ticker: "SHIP", name: "Silmaril Samudera Tbk", sector: "Energy" },
  { ticker: "SICO", name: "Sigma Energy Compressindo Tbk", sector: "Energy" },
  { ticker: "SMMT", name: "Golden Eagle Energy Tbk", sector: "Energy" },
  { ticker: "SOCHI", name: "Soechi Lines Tbk", sector: "Energy" },
  { ticker: "SURE", name: "Super Energy Tbk", sector: "Energy" },
  { ticker: "TAMU", name: "Pelayaran Tamarin Samudra Tbk", sector: "Energy" },
  { ticker: "TEBE", name: "Dana Brata Luhur Tbk", sector: "Energy" },
  { ticker: "TOBA", name: "TBS Energi Utama Tbk", sector: "Energy" },
  { ticker: "TRAM", name: "Trada Alam Minera Tbk", sector: "Energy" },
  { ticker: "WAPO", name: "Wahana Pronatural Tbk", sector: "Energy" },
  { ticker: "WINE", name: "Hatten Bali Tbk", sector: "Energy" },
  { ticker: "WOWS", name: "Ginting Jaya Energi Tbk", sector: "Energy" },

  // ─── 3. BASIC MATERIALS (133 Emiten) ───
  { ticker: "ADMG", name: "Polychem Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "AGII", name: "Samator Indo Gas Tbk", sector: "Basic Materials" },
  { ticker: "ALDO", name: "Alkindo Naratama Tbk", sector: "Basic Materials" },
  { ticker: "ALKA", name: "Alakasa Industrindo Tbk", sector: "Basic Materials" },
  { ticker: "ALMI", name: "Alumindo Light Metal Industry Tbk", sector: "Basic Materials" },
  { ticker: "AMFG", name: "Asahimas Flat Glass Tbk", sector: "Basic Materials" },
  { ticker: "AMMN", name: "Amman Mineral Internasional Tbk", sector: "Basic Materials" },
  { ticker: "ANTM", name: "Aneka Tambang Tbk", sector: "Basic Materials" },
  { ticker: "APLI", name: "Asiaplast Industries Tbk", sector: "Basic Materials" },
  { ticker: "ARCI", name: "Archi Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "ARNA", name: "Arwana Citramulia Tbk", sector: "Basic Materials" },
  { ticker: "ASLI", name: "Asri Pancawarna Tbk", sector: "Basic Materials" },
  { ticker: "AVIA", name: "Avia Avian Tbk", sector: "Basic Materials" },
  { ticker: "AYLS", name: "Agro Yasa Lestari Tbk", sector: "Basic Materials" },
  { ticker: "BATR", name: "Benteng Multi Indotbk", sector: "Basic Materials" },
  { ticker: "BAUT", name: "Mitra Angkasa Sejahtera Tbk", sector: "Basic Materials" },
  { ticker: "BBMD", name: "Bank Mestika Dharma Tbk", sector: "Basic Materials" },
  { ticker: "BEBS", name: "Berkah Beton Sadaya Tbk", sector: "Basic Materials" },
  { ticker: "BLES", name: "Superior Prima Sukses Tbk", sector: "Basic Materials" },
  { ticker: "BMSR", name: "Bintang Mitra Semestaraya Tbk", sector: "Basic Materials" },
  { ticker: "BOBA", name: "Formosa Ingredient Factory Tbk", sector: "Basic Materials" },
  { ticker: "BOGA", name: "Bintang Oto Global Tbk", sector: "Basic Materials" },
  { ticker: "BRAM", name: "Indo Kordsa Tbk", sector: "Basic Materials" },
  { ticker: "BRMS", name: "Bumi Resources Minerals Tbk", sector: "Basic Materials" },
  { ticker: "BRNA", name: "Berlina Tbk", sector: "Basic Materials" },
  { ticker: "BRPT", name: "Barito Pacific Tbk", sector: "Basic Materials" },
  { ticker: "BTON", name: "Betonjaya Manunggal Tbk", sector: "Basic Materials" },
  { ticker: "CAKK", name: "Cahayaputra Asa Keramik Tbk", sector: "Basic Materials" },
  { ticker: "CBPE", name: "Citra Borneo Utama Tbk", sector: "Basic Materials" },
  { ticker: "CHEM", name: "Chemstar Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "CINT", name: "Chitose Internasional Tbk", sector: "Basic Materials" },
  { ticker: "CITA", name: "Cita Mineral Investindo Tbk", sector: "Basic Materials" },
  { ticker: "CLPI", name: "Colorpak Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "CMNT", name: "Cemindo Gemilang Tbk", sector: "Basic Materials" },
  { ticker: "COIN", name: "Central Omega Resources Tbk", sector: "Basic Materials" },
  { ticker: "CTBN", name: "Citra Tubindo Tbk", sector: "Basic Materials" },
  { ticker: "CTTH", name: "Citatah Tbk", sector: "Basic Materials" },
  { ticker: "DAAZ", name: "Daaz Bara Lestari Tbk", sector: "Basic Materials" },
  { ticker: "DKFT", name: "Central Omega Resources Tbk", sector: "Basic Materials" },
  { ticker: "DPNS", name: "Duta Pertiwi Nusantara Tbk", sector: "Basic Materials" },
  { ticker: "DYNA", name: "Dynaplast Tbk", sector: "Basic Materials" },
  { ticker: "EKAD", name: "Ekadharma International Tbk", sector: "Basic Materials" },
  { ticker: "EPAC", name: "Megalestari Epack Sentosaraya Tbk", sector: "Basic Materials" },
  { ticker: "ESIP", name: "Sinergi Inti Plastindo Tbk", sector: "Basic Materials" },
  { ticker: "ESSA", name: "ESSA Industries Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "ETWA", name: "Eterindo Wahanatama Tbk", sector: "Basic Materials" },
  { ticker: "FASW", name: "Fajar Surya Wisesa Tbk", sector: "Basic Materials" },
  { ticker: "FLEX", name: "Flexi Pack Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "FLMC", name: "Falmaco Nonwoven Industri Tbk", sector: "Basic Materials" },
  { ticker: "FPNI", name: "Lotte Chemical Titan Tbk", sector: "Basic Materials" },
  { ticker: "FWCT", name: "Wijaya Cahaya Timber Tbk", sector: "Basic Materials" },
  { ticker: "GDST", name: "Gunawan Dianjaya Steel Tbk", sector: "Basic Materials" },
  { ticker: "GSTM", name: "Gunung Selang Tbk", sector: "Basic Materials" },
  { ticker: "IFII", name: "Indonesia Fibreboard Industry Tbk", sector: "Basic Materials" },
  { ticker: "IFSH", name: "Ifishdeco Tbk", sector: "Basic Materials" },
  { ticker: "IGAR", name: "Champion Pacific Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "IKAI", name: "Intikeramik Alamasri Industri Tbk", sector: "Basic Materials" },
  { ticker: "INAI", name: "Indal Aluminium Industry Tbk", sector: "Basic Materials" },
  { ticker: "INCI", name: "Intanwijaya Internasional Tbk", sector: "Basic Materials" },
  { ticker: "INCO", name: "Vale Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "INKP", name: "Indah Kiat Pulp & Paper Tbk", sector: "Basic Materials" },
  { ticker: "INRU", name: "Toba Pulp Lestari Tbk", sector: "Basic Materials" },
  { ticker: "INTP", name: "Indocement Tunggal Prakarsa Tbk", sector: "Basic Materials" },
  { ticker: "ISSP", name: "Steel Pipe Industry of Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "JKSW", name: "Jakarta Kyoei Steel Works Tbk", sector: "Basic Materials" },
  { ticker: "KBAG", name: "Karya Bersama Anugerah Tbk", sector: "Basic Materials" },
  { ticker: "KDSI", name: "Kedawung Setia Industrial Tbk", sector: "Basic Materials" },
  { ticker: "KIAS", name: "Keramika Indonesia Assosiasi Tbk", sector: "Basic Materials" },
  { ticker: "KMTR", name: "Kirana Megatara Tbk", sector: "Basic Materials" },
  { ticker: "KOIN", name: "Kokoh Inti Arebama Tbk", sector: "Basic Materials" },
  { ticker: "KRAS", name: "Krakatau Steel (Persero) Tbk", sector: "Basic Materials" },
  { ticker: "KRYA", name: "Bangun Karya Perkasa Jaya Tbk", sector: "Basic Materials" },
  { ticker: "KUAS", name: "Ace Oldfields Tbk", sector: "Basic Materials" },
  { ticker: "LABA", name: "Ladangbaja Murni Tbk", sector: "Basic Materials" },
  { ticker: "LMPI", name: "Langgeng Makmur Industri Tbk", sector: "Basic Materials" },
  { ticker: "LTLS", name: "Lautans Luas Tbk", sector: "Basic Materials" },
  { ticker: "MARK", name: "Mark Dynamics Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "MBMA", name: "Merdeka Battery Materials Tbk", sector: "Basic Materials" },
  { ticker: "MDKA", name: "Merdeka Copper Gold Tbk", sector: "Basic Materials" },
  { ticker: "MDKI", name: "Emdeki Utama Tbk", sector: "Basic Materials" },
  { ticker: "MHKI", name: "Maja Graha Kencana Tbk", sector: "Basic Materials" },
  { ticker: "MLIA", name: "Mulia Industrindo Tbk", sector: "Basic Materials" },
  { ticker: "MOLI", name: "Madusari Murni Indah Tbk", sector: "Basic Materials" },
  { ticker: "NAIK", name: "Adhi Kartiko Pratama Tbk", sector: "Basic Materials" },
  { ticker: "NCKL", name: "Trimegah Bangun Persada Tbk", sector: "Basic Materials" },
  { ticker: "NICE", name: "Adhi Kartiko Pratama Tbk", sector: "Basic Materials" },
  { ticker: "NICL", name: "PAM Mineral Tbk", sector: "Basic Materials" },
  { ticker: "NIKL", name: "Pelat Timah Nusantara Tbk", sector: "Basic Materials" },
  { ticker: "NPGF", name: "Nusa Palapa Gemilang Tbk", sector: "Basic Materials" },
  { ticker: "OKAS", name: "Ancora Indonesia Resources Tbk", sector: "Basic Materials" },
  { ticker: "OPMS", name: "Optima Prima Metal Sinergi Tbk", sector: "Basic Materials" },
  { ticker: "PACK", name: "Solusi Kemasan Digital Tbk", sector: "Basic Materials" },
  { ticker: "PADA", name: "Pebana Dinamika Tbk", sector: "Basic Materials" },
  { ticker: "PBID", name: "Panca Budi Idaman Tbk", sector: "Basic Materials" },
  { ticker: "PICO", name: "Pelangi Indah Canindo Tbk", sector: "Basic Materials" },
  { ticker: "PRAY", name: "Famon Awal Bros Sedaya Tbk", sector: "Basic Materials" },
  { ticker: "PRSN", name: "Prasidha Aneka Niaga Tbk", sector: "Basic Materials" },
  { ticker: "PSAB", name: "J Resources Asia Pasifik Tbk", sector: "Basic Materials" },
  { ticker: "PURE", name: "Trinitan Metals and Minerals Tbk", sector: "Basic Materials" },
  { ticker: "SAMF", name: "Saraswanti Anugerah Makmur Tbk", sector: "Basic Materials" },
  { ticker: "SBMA", name: "Surya Biru Murni Acetylene Tbk", sector: "Basic Materials" },
  { ticker: "SGGO", name: "Samator Indo Gas Tbk", sector: "Basic Materials" },
  { ticker: "SIMA", name: "Siwani Makmur Tbk", sector: "Basic Materials" },
  { ticker: "SMBR", name: "Semen Baturaja Tbk", sector: "Basic Materials" },
  { ticker: "SMCB", name: "Solusi Bangun Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "SMGA", name: "Sumber Mineral Global Abadi Tbk", sector: "Basic Materials" },
  { ticker: "SMGR", name: "Semen Indonesia (Persero) Tbk", sector: "Basic Materials" },
  { ticker: "SMKL", name: "Cipta Selera Murni Tbk", sector: "Basic Materials" },
  { ticker: "SOLA", name: "Xolare Reka Sejahtera Tbk", sector: "Basic Materials" },
  { ticker: "SPMA", name: "Suparma Tbk", sector: "Basic Materials" },
  { ticker: "SQMI", name: "Wilton Makmur Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "SRIN", name: "Sinar Riau Indah Tbk", sector: "Basic Materials" },
  { ticker: "SRSN", name: "Indo Acidatama Tbk", sector: "Basic Materials" },
  { ticker: "STRK", name: "Batu Gunung Mulia Tbk", sector: "Basic Materials" },
  { ticker: "SULI", name: "SLJ Global Tbk", sector: "Basic Materials" },
  { ticker: "SUNR", name: "Sunindo Pratama Tbk", sector: "Basic Materials" },
  { ticker: "SWAT", name: "Sriwahana Adityakarta Tbk", sector: "Basic Materials" },
  { ticker: "TAYS", name: "Jaya Swarasa Agung Tbk", sector: "Basic Materials" },
  { ticker: "TBMS", name: "Tembaga Mulia Semanan Tbk", sector: "Basic Materials" },
  { ticker: "TDPM", name: "Tridomain Performance Materials Tbk", sector: "Basic Materials" },
  { ticker: "TINS", name: "Timah Tbk", sector: "Basic Materials" },
  { ticker: "TIRA", name: "Tira Austenite Tbk", sector: "Basic Materials" },
  { ticker: "TIRT", name: "Tirta Mahakam Resources Tbk", sector: "Basic Materials" },
  { ticker: "TKIM", name: "Pabrik Kertas Tjiwi Kimia Tbk", sector: "Basic Materials" },
  { ticker: "TOTO", name: "Surya Toto Indonesia Tbk", sector: "Basic Materials" },
  { ticker: "TPIA", name: "Chandra Asri Pacific Tbk", sector: "Basic Materials" },
  { ticker: "TRST", name: "Trias Sentosa Tbk", sector: "Basic Materials" },
  { ticker: "TYMT", name: "Timah Industri Tbk", sector: "Basic Materials" },
  { ticker: "UNIC", name: "Unggul Indah Cahaya Tbk", sector: "Basic Materials" },
  { ticker: "UNTD", name: "Terang Dunia Internusa Tbk", sector: "Basic Materials" },
  { ticker: "WSBP", name: "Waskita Beton Precast Tbk", sector: "Basic Materials" },
  { ticker: "WTON", name: "Wijaya Karya Beton Tbk", sector: "Basic Materials" },
  { ticker: "YPAS", name: "Yanaprima Hastapersada Tbk", sector: "Basic Materials" },

  // ─── 4. INFRASTRUCTURES (56 Emiten) ───
  { ticker: "ACST", name: "Acset Indonusa Tbk", sector: "Infrastructures" },
  { ticker: "ADHI", name: "Adhi Karya (Persero) Tbk", sector: "Infrastructures" },
  { ticker: "ARKO", name: "Arkora Hydro Tbk", sector: "Infrastructures" },
  { ticker: "BALI", name: "Bali Towerindo Sentra Tbk", sector: "Infrastructures" },
  { ticker: "BDKR", name: "Berdaya Bersama Semesta Tbk", sector: "Infrastructures" },
  { ticker: "BREN", name: "Barito Renewables Energy Tbk", sector: "Infrastructures" },
  { ticker: "BUKK", name: "Bukaka Teknik Utama Tbk", sector: "Infrastructures" },
  { ticker: "CENT", name: "Centratama Telekomunikasi Indonesia Tbk", sector: "Infrastructures" },
  { ticker: "CMNP", name: "Citra Marga Nusaphala Persada Tbk", sector: "Infrastructures" },
  { ticker: "DGIK", name: "Nusa Konstruksi Enjiniring Tbk", sector: "Infrastructures" },
  { ticker: "DUTA", name: "Duta Sarana Mandiri Tbk", sector: "Infrastructures" },
  { ticker: "EXCL", name: "XL Axiata Tbk", sector: "Infrastructures" },
  { ticker: "FIMP", name: "Fimperkasa Utama Tbk", sector: "Infrastructures" },
  { ticker: "FREN", name: "Smartfren Telecom Tbk", sector: "Infrastructures" },
  { ticker: "GHON", name: "Gihon Telekomunikasi Indonesia Tbk", sector: "Infrastructures" },
  { ticker: "IBST", name: "Inti Bangun Sejahtera Tbk", sector: "Infrastructures" },
  { ticker: "IDPR", name: "Indonesia Pondasi Raya Tbk", sector: "Infrastructures" },
  { ticker: "INET", name: "Sinergi Inti Andalan Prima Tbk", sector: "Infrastructures" },
  { ticker: "ISAT", name: "Indosat Ooredoo Hutchison Tbk", sector: "Infrastructures" },
  { ticker: "JECC", name: "Jembo Cable Company Tbk", sector: "Infrastructures" },
  { ticker: "JKON", name: "Jaya Konstruksi Manggala Pratama Tbk", sector: "Infrastructures" },
  { ticker: "JSMR", name: "Jasa Marga (Persero) Tbk", sector: "Infrastructures" },
  { ticker: "KBLI", name: "KMI Wire & Cable Tbk", sector: "Infrastructures" },
  { ticker: "KBLM", name: "Kabelindo Murni Tbk", sector: "Infrastructures" },
  { ticker: "KEEN", name: "Kencana Energi Lestari Tbk", sector: "Infrastructures" },
  { ticker: "KOKA", name: "Koka Indonesia Tbk", sector: "Infrastructures" },
  { ticker: "LCKM", name: "LCK Global Kedaton Tbk", sector: "Infrastructures" },
  { ticker: "MANG", name: "Manggung Polahraya Tbk", sector: "Infrastructures" },
  { ticker: "META", name: "Nusantara Infrastructure Tbk", sector: "Infrastructures" },
  { ticker: "MTAL", name: "Mitra Pemuda Tbk", sector: "Infrastructures" },
  { ticker: "MTEL", name: "Dayamitra Telekomunikasi Tbk", sector: "Infrastructures" },
  { ticker: "MTO", name: "Mitra Telco Nusantara Tbk", sector: "Infrastructures" },
  { ticker: "MTPS", name: "Meta Epsi Tbk", sector: "Infrastructures" },
  { ticker: "NRCA", name: "Nusa Raya Cipta Tbk", sector: "Infrastructures" },
  { ticker: "NUSA", name: "Nusantara Infrastructure Tbk", sector: "Infrastructures" },
  { ticker: "OASA", name: "Maharaksa Biru Energi Tbk", sector: "Infrastructures" },
  { ticker: "PBMM", name: "Pelita Bangun Mandiri Tbk", sector: "Infrastructures" },
  { ticker: "PGEO", name: "Pertamina Geothermal Energy Tbk", sector: "Infrastructures" },
  { ticker: "POWR", name: "Cikarang Listrindo Tbk", sector: "Infrastructures" },
  { ticker: "PPRE", name: "PP Presisi Tbk", sector: "Infrastructures" },
  { ticker: "PTDU", name: "Djasa Ubersakti Tbk", sector: "Infrastructures" },
  { ticker: "PTPP", name: "PP (Persero) Tbk", sector: "Infrastructures" },
  { ticker: "RONY", name: "Omni Inovasi Rekasindo Tbk", sector: "Infrastructures" },
  { ticker: "SCCO", name: "Supreme Cable Manufacturing & Commerce Tbk", sector: "Infrastructures" },
  { ticker: "TAMA", name: "Lancartama Sejati Tbk", sector: "Infrastructures" },
  { ticker: "TBIG", name: "Tower Bersama Infrastructure Tbk", sector: "Infrastructures" },
  { ticker: "TGRA", name: "Terregra Asia Energy Tbk", sector: "Infrastructures" },
  { ticker: "TLKM", name: "Telkom Indonesia (Persero) Tbk", sector: "Infrastructures" },
  { ticker: "TOPS", name: "Totalindo Eka Persada Tbk", sector: "Infrastructures" },
  { ticker: "TOTL", name: "Total Bangun Persada Tbk", sector: "Infrastructures" },
  { ticker: "TOWR", name: "Sarana Menara Nusantara Tbk", sector: "Infrastructures" },
  { ticker: "VAWS", name: "Visi Artha Wisesa Tbk", sector: "Infrastructures" },
  { ticker: "VOKS", name: "Voksel Electric Tbk", sector: "Infrastructures" },
  { ticker: "WEGE", name: "Wijaya Karya Bangunan Gedung Tbk", sector: "Infrastructures" },
  { ticker: "WIKA", name: "Wijaya Karya (Persero) Tbk", sector: "Infrastructures" },
  { ticker: "WSKT", name: "Waskita Karya (Persero) Tbk", sector: "Infrastructures" },

  // ─── 5. CONSUMER NON-CYCLICALS (109 Emiten) ───
  { ticker: "AALI", name: "Astra Agro Lestari Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ADES", name: "Akasha Wira International Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "AGAR", name: "Asia Sejahtera Mina Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "AGRI", name: "Agro Sentosa Prima Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "AISA", name: "FKS Food Sejahtera Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ALTO", name: "Tri Banyan Tirta Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "AMRT", name: "Sumber Alfaria Trijaya Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ANDI", name: "Andira Agro Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ANJT", name: "Austindo Nusantara Jaya Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "BEEF", name: "Estika Tata Tiara Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "BEER", name: "Jobi Beer Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "BISI", name: "BISI International Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "BOPO", name: "Bumi Teknokultura Unggul Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "BTEK", name: "Bumi Teknokultura Unggul Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "BUDI", name: "Budi Starch & Sweetener Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "BWPT", name: "Eagle High Plantations Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CAMP", name: "Campina Ice Cream Industry Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CBMF", name: "Cahaya Bintang Medan Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CEKA", name: "Wilmar Cahaya Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CLEO", name: "Sariguna Primatirta Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CMRY", name: "Cisarua Mountain Dairy Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "COCO", name: "Wahana Interfood Nusantara Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CPIN", name: "Charoen Pokphand Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CPRO", name: "Central Proteina Prima Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CRAB", name: "Mitra Pemuda Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "CSRA", name: "Cisadane Sawit Raya Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "DLTA", name: "Delta Djakarta Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "DMND", name: "Diamond Food Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "DNET", name: "Indoritel Makmur Internasional Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "DSFI", name: "Dharma Samudera Fishing Industries Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "DSNG", name: "Dharma Satya Nusantara Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "EKA", name: "Eka Boga Inti Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ENAG", name: "Eka Nusa Agri Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ENZO", name: "Morenzo Abadi Perkasa Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "EURO", name: "Estetika Tata Tiara Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "FAPA", name: "FAP Agri Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "FISH", name: "FKS Multi Agro Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "FOOD", name: "Sentra Food Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "GGRM", name: "Gudang Garam Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "GOOD", name: "Garudafood Putra Putri Jaya Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "GUNA", name: "Gunanusa Eramandiri Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "GZCO", name: "Gozco Plantations Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "HERO", name: "Hero Supermarket Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "HMSP", name: "H.M. Sampoerna Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "HOKI", name: "Buyung Poetra Sembada Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "IBOS", name: "Indo Boga Sukses Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ICBP", name: "Indofood CBP Sukses Makmur Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "IIKP", name: "Inti Agri Resources Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "IKAN", name: "Era Mandiri Cemerlang Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "INDF", name: "Indofood Sukses Makmur Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "IPPE", name: "Inovisi Infracom Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ITIC", name: "Indonesian Tobacco Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "JARR", name: "Jhonlin Agro Raya Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "JATI", name: "Jati Agro Lestari Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "JAWA", name: "Jaya Agra Wattie Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "JPFA", name: "Japfa Comfeed Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "KAYU", name: "Darmi Bersaudara Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "KEJU", name: "Mulia Boga Raya Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "KICI", name: "Kedaung Indah Can Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "LSIP", name: "PP London Sumatra Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "MAGP", name: "Multi Agro Gemilang Plantation Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "MAIN", name: "Malindo Feedmill Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "MAXI", name: "Maxindo Karya Anugerah Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "MGRO", name: "Mahkota Group Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "MIDI", name: "Midi Utama Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "MKTR", name: "Menthobi Karyatama Raya Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "MLBI", name: "Multi Bintang Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "MYOR", name: "Mayora Indah Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "NASI", name: "Wahana Inti Makmur Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "NAYZ", name: "Hassana Boga Sejahtera Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "NEST", name: "Janu Putra Sejahtera Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "NSSS", name: "Nusantara Sawit Sejahtera Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "NTBK", name: "Nusantara Pelestari Air Minum Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "PALM", name: "Provident Investasi Bersama Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "PANI", name: "Pantai Indah Kapuk Dua Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "PCAR", name: "Prima Cakrawala Abadi Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "PGUN", name: "Pradiksi Gunatama Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "PHST", name: "Pusaka Harapan Sentosa Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "PMMP", name: "Panca Mitra Multiperdana Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "PSGO", name: "Palma Serasih Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "PTPS", name: "Pulau Subur Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "RAFI", name: "Sari Kreasi Boga Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "RANC", name: "Supra Boga Lestari Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ROTI", name: "Nippon Indosari Corpindo Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SIMP", name: "Salim Ivomas Pratama Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SIPD", name: "Sreeya Sewu Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SKBM", name: "Sekar Bumi Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SKLT", name: "Sekar Laut Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SKRN", name: "Superkrane Mitra Utama Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SMAR", name: "Sinar Mas Agro Resources and Technology Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SMLE", name: "Sinergi Multi Lestarindo Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SNLK", name: "Sunter Lakeside Hotel Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SOUL", name: "Mitra Tirta Buwana Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "SSMS", name: "Sawit Sumbermas Sarana Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "STAA", name: "Sumber Tani Agung Resources Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "STTP", name: "Siantar Top Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "TAPG", name: "Triputra Agro Persada Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "TBLA", name: "Tunas Baru Lampung Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "TCID", name: "Mandom Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "TGKA", name: "Tigaraksa Satria Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "TLDN", name: "Teladan Prima Agro Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "TRGU", name: "Cerestar Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "UCID", name: "Uni-Charm Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "ULTJ", name: "Ultra Jaya Milk Industry & Trading Co Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "UNVR", name: "Unilever Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "VICI", name: "Victoria Care Indonesia Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "WIIM", name: "Wismilak Inti Makmur Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "WMPP", name: "Widodo Makmur Perkasa Tbk", sector: "Consumer Non-Cyclicals" },
  { ticker: "WMUU", name: "Widodo Makmur Unggas Tbk", sector: "Consumer Non-Cyclicals" },

  // ─── 6. CONSUMER CYCLICALS (112 Emiten) ───
  { ticker: "ACES", name: "Aspirasi Hidup Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ACRO", name: "Samcro Hyosung Adilestari Tbk", sector: "Consumer Cyclicals" },
  { ticker: "AMMS", name: "Agung Menjangan Mas Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ARTA", name: "Arthavest Tbk", sector: "Consumer Cyclicals" },
  { ticker: "AUTO", name: "Astra Otoparts Tbk", sector: "Consumer Cyclicals" },
  { ticker: "AYAM", name: "Jayamas Medica Industri Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BABY", name: "Era Media Sejahtera Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BAIC", name: "Beijing Automotive Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BAJA", name: "Saranacentral Bajatama Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BATA", name: "Sepatu Bata Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BATX", name: "Bata Industri Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BAYU", name: "Bayu Buana Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BELL", name: "Trisula Textile Industries Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BIKE", name: "Sepeda Bersama Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "BIPP", name: "Bhuwanatala Indah Permai Tbk", sector: "Consumer Cyclicals" },
  { ticker: "CARS", name: "Bintraco Dharma Tbk", sector: "Consumer Cyclicals" },
  { ticker: "CHIP", name: "Pelita Teknologi Global Tbk", sector: "Consumer Cyclicals" },
  { ticker: "CLAY", name: "Citra Putra Realty Tbk", sector: "Consumer Cyclicals" },
  { ticker: "CNMA", name: "Nusantara Sejahtera Raya Tbk (Cinema XXI)", sector: "Consumer Cyclicals" },
  { ticker: "CNTX", name: "Century Textile Industry Tbk", sector: "Consumer Cyclicals" },
  { ticker: "CSAP", name: "Catur Sentosa Adiprana Tbk", sector: "Consumer Cyclicals" },
  { ticker: "CSIS", name: "Cahayasakti Investindo Sukses Tbk", sector: "Consumer Cyclicals" },
  { ticker: "CSMI", name: "Cipta Selera Murni Tbk", sector: "Consumer Cyclicals" },
  { ticker: "DAYA", name: "Duta Intidaya Tbk", sector: "Consumer Cyclicals" },
  { ticker: "DEPO", name: "Caturkarda Depo Bangunan Tbk", sector: "Consumer Cyclicals" },
  { ticker: "DFAM", name: "Dafam Property Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "DOOH", name: "Era Media Kreatif Tbk", sector: "Consumer Cyclicals" },
  { ticker: "DRMA", name: "Dharma Polimetal Tbk", sector: "Consumer Cyclicals" },
  { ticker: "EAST", name: "Eastparc Hotel Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ECII", name: "Electronic City Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "EPRT", name: "Electronic City Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ERAA", name: "Erajaya Swasembada Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ERAL", name: "Sinar Eka Selaras Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ERTX", name: "Eratex Djaja Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ESTA", name: "Esta Multi Usaha Tbk", sector: "Consumer Cyclicals" },
  { ticker: "FAST", name: "Fast Food Indonesia Tbk (KFC)", sector: "Consumer Cyclicals" },
  { ticker: "FILM", name: "MD Pictures Tbk", sector: "Consumer Cyclicals" },
  { ticker: "FITT", name: "Hotel Fitra International Tbk", sector: "Consumer Cyclicals" },
  { ticker: "FOCI", name: "Focus Media Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "FORU", name: "Fortune Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "GDYR", name: "Goodyear Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "GEMA", name: "Gema Grahasarana Tbk", sector: "Consumer Cyclicals" },
  { ticker: "GJTL", name: "Gajah Tunggal Tbk", sector: "Consumer Cyclicals" },
  { ticker: "GLOB", name: "Global Teleshop Tbk", sector: "Consumer Cyclicals" },
  { ticker: "GOLD", name: "Visi Telekomunikasi Infrastruktur Tbk", sector: "Consumer Cyclicals" },
  { ticker: "GOLF", name: "Intra GolfLink Resorts Tbk", sector: "Consumer Cyclicals" },
  { ticker: "GULA", name: "Aman Agrindo Tbk", sector: "Consumer Cyclicals" },
  { ticker: "HDTX", name: "Panasia Indo Resources Tbk", sector: "Consumer Cyclicals" },
  { ticker: "HOME", name: "Hotel Mandarine Regency Tbk", sector: "Consumer Cyclicals" },
  { ticker: "HOTL", name: "Saraswati Griya Lestari Tbk", sector: "Consumer Cyclicals" },
  { ticker: "HRME", name: "Menteng Heritage Realty Tbk", sector: "Consumer Cyclicals" },
  { ticker: "HRTA", name: "Hartadinata Abadi Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ICON", name: "Island Concepts Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "IMAS", name: "Indomobil Sukses Internasional Tbk", sector: "Consumer Cyclicals" },
  { ticker: "INDR", name: "Indo-Rama Synthetics Tbk", sector: "Consumer Cyclicals" },
  { ticker: "INPP", name: "Indonesian Paradise Property Tbk", sector: "Consumer Cyclicals" },
  { ticker: "INTD", name: "Inter Delta Tbk", sector: "Consumer Cyclicals" },
  { ticker: "INVS", name: "Inovisi Infracom Tbk", sector: "Consumer Cyclicals" },
  { ticker: "IPTV", name: "MNC Vision Networks Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ISAP", name: "Isra Presisi Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "JGLE", name: "Graha Andrasentra Propertindo Tbk", sector: "Consumer Cyclicals" },
  { ticker: "JIHD", name: "Jakarta International Hotels & Development Tbk", sector: "Consumer Cyclicals" },
  { ticker: "JSPT", name: "Jakarta Setiabudi Internasional Tbk", sector: "Consumer Cyclicals" },
  { ticker: "KBLV", name: "First Media Tbk", sector: "Consumer Cyclicals" },
  { ticker: "KIEV", name: "Kencana Abadi Jaya Tbk", sector: "Consumer Cyclicals" },
  { ticker: "KOTA", name: "DMS Propertindo Tbk", sector: "Consumer Cyclicals" },
  { ticker: "KPIG", name: "MNC Land Tbk", sector: "Consumer Cyclicals" },
  { ticker: "LIVE", name: "Homeco Victoria Makmur Tbk", sector: "Consumer Cyclicals" },
  { ticker: "LMAS", name: "Limas Indonesia Makmur Tbk", sector: "Consumer Cyclicals" },
  { ticker: "LPPF", name: "Matahari Department Store Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MABA", name: "Marga Abhinaya Abadi Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MAJU", name: "Maju Bersama Sejahtera Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MAMH", name: "Graha Multi Bintang Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MAMI", name: "Mas Murni Indonesia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MAPA", name: "MAP Aktif Adiperkasa Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MAPB", name: "MAP Boga Adiperkasa Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MAPI", name: "Mitra Adiperkasa Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MDIA", name: "Intermedia Capital Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MEJA", name: "Harta Djaya Karya Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MICE", name: "Multi Indocitra Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MINA", name: "Sanurhasta Mitra Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MNCN", name: "Media Nusantara Citra Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MPMX", name: "Mitra Pinasthika Mustika Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MPOW", name: "Megapower Makmur Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MPPA", name: "Matahari Putra Prima Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MSIN", name: "MNC Digital Entertainment Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MSKY", name: "MNC Sky Vision Tbk", sector: "Consumer Cyclicals" },
  { ticker: "MYTX", name: "Asia Pacific Investama Tbk", sector: "Consumer Cyclicals" },
  { ticker: "NETV", name: "Net Visi Media Tbk", sector: "Consumer Cyclicals" },
  { ticker: "PANR", name: "Panorama Transportasi Tbk", sector: "Consumer Cyclicals" },
  { ticker: "PBRX", name: "Pan Brothers Tbk", sector: "Consumer Cyclicals" },
  { ticker: "PGLI", name: "Pembangunan Graha Lestari Indah Tbk", sector: "Consumer Cyclicals" },
  { ticker: "PMJS", name: "Putra Mandiri Jembar Tbk", sector: "Consumer Cyclicals" },
  { ticker: "PZZA", name: "Sarimelati Kencana Tbk (Pizza Hut)", sector: "Consumer Cyclicals" },
  { ticker: "RAAM", name: "Tripar Multivision Plus Tbk", sector: "Consumer Cyclicals" },
  { ticker: "RALS", name: "Ramayana Lestari Sentosa Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SAKR", name: "Satria Mega Kencana Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SCMA", name: "Surya Citra Media Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SHID", name: "Hotel Sahid Jaya International Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SLIS", name: "Gaya Abadi Sempurna Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SMSM", name: "Selamat Sempurna Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SOFA", name: "Boston Furniture Industries Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SONA", name: "Sona Topas Tourism Industry Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SRIL", name: "Sri Rejeki Isman Tbk", sector: "Consumer Cyclicals" },
  { ticker: "SSTM", name: "Sunson Textile Manufacturer Tbk", sector: "Consumer Cyclicals" },
  { ticker: "TMPO", name: "Tempo Inti Media Tbk", sector: "Consumer Cyclicals" },
  { ticker: "TOOL", name: "Rohartindo Nusantara Luas Tbk", sector: "Consumer Cyclicals" },
  { ticker: "TRIS", name: "Trisula International Tbk", sector: "Consumer Cyclicals" },
  { ticker: "TURI", name: "Tunas Ridean Tbk", sector: "Consumer Cyclicals" },
  { ticker: "VIVA", name: "Visi Media Asia Tbk", sector: "Consumer Cyclicals" },
  { ticker: "WOOD", name: "Integra Indocabinet Tbk", sector: "Consumer Cyclicals" },
  { ticker: "ZATA", name: "Bersama Zatta Jaya Tbk", sector: "Consumer Cyclicals" },

  // ─── 7. INDUSTRIALS (78 Emiten) ───
  { ticker: "AMIN", name: "Ateliers Mecaniques D Indonesie Tbk", sector: "Industrials" },
  { ticker: "APII", name: "Arita Prima Indonesia Tbk", sector: "Industrials" },
  { ticker: "ARGO", name: "Argo Pantes Tbk", sector: "Industrials" },
  { ticker: "ARKA", name: "Arkha Jayanti Persada Tbk", sector: "Industrials" },
  { ticker: "ASGR", name: "Astra Graphia Tbk", sector: "Industrials" },
  { ticker: "ASII", name: "Astra International Tbk", sector: "Industrials" },
  { ticker: "ASLC", name: "Autopedia Sukses Lestari Tbk", sector: "Industrials" },
  { ticker: "BIMA", name: "Primarindo Asia Infrastructure Tbk", sector: "Industrials" },
  { ticker: "BINO", name: "Perma Plasindo Tbk", sector: "Industrials" },
  { ticker: "BLTZ", name: "Graha Layar Prima Tbk", sector: "Industrials" },
  { ticker: "BMBL", name: "Lavender Tiga Cendikia Tbk", sector: "Industrials" },
  { ticker: "BMTR", name: "Global Mediacom Tbk", sector: "Industrials" },
  { ticker: "BNBR", name: "Bakrie & Brothers Tbk", sector: "Industrials" },
  { ticker: "BOLT", name: "Garuda Metalindo Tbk", sector: "Industrials" },
  { ticker: "CARA", name: "Cahaya Raya Abadi Tbk", sector: "Industrials" },
  { ticker: "CCSI", name: "Communication Cable Systems Indonesia Tbk", sector: "Industrials" },
  { ticker: "CMSP", name: "Central Motor Wheels Tbk", sector: "Industrials" },
  { ticker: "CRSN", name: "Carsurin Tbk", sector: "Industrials" },
  { ticker: "DYAN", name: "Dyandra Media International Tbk", sector: "Industrials" },
  { ticker: "ESTI", name: "Ever Shine Tex Tbk", sector: "Industrials" },
  { ticker: "GMFI", name: "Garuda Maintenance Facility Aero Asia Tbk", sector: "Industrials" },
  { ticker: "GPSO", name: "Geoprima Solusi Tbk", sector: "Industrials" },
  { ticker: "HEXA", name: "Hexindo Adiperkasa Tbk", sector: "Industrials" },
  { ticker: "HOPE", name: "Harapan Duta Pertiwi Tbk", sector: "Industrials" },
  { ticker: "HYGN", name: "Ecocare Indo Pasifik Tbk", sector: "Industrials" },
  { ticker: "IKBI", name: "Sumi Indo Kabel Tbk", sector: "Industrials" },
  { ticker: "IMPC", name: "Impack Pratama Industri Tbk", sector: "Industrials" },
  { ticker: "INDO", name: "Royalindo Investa Wijaya Tbk", sector: "Industrials" },
  { ticker: "INDS", name: "Indospring Tbk", sector: "Industrials" },
  { ticker: "INOV", name: "Inocycle Technology Group Tbk", sector: "Industrials" },
  { ticker: "INTA", name: "Intraco Penta Tbk", sector: "Industrials" },
  { ticker: "IPAC", name: "Era Media Sejahtera Tbk", sector: "Industrials" },
  { ticker: "JTPE", name: "Jasuindo Tiga Perkasa Tbk", sector: "Industrials" },
  { ticker: "KDTN", name: "Puri Sentul Permai Tbk", sector: "Industrials" },
  { ticker: "KING", name: "Hoffmen Cleanindo Tbk", sector: "Industrials" },
  { ticker: "KLAS", name: "Pelayaran Kurnia Lautan Semesta Tbk", sector: "Industrials" },
  { ticker: "KMDS", name: "Kurniamitra Duta Sentosa Tbk", sector: "Industrials" },
  { ticker: "KOBX", name: "Kobexindo Tractors Tbk", sector: "Industrials" },
  { ticker: "KPAL", name: "Steadfast Marine Tbk", sector: "Industrials" },
  { ticker: "KPAS", name: "Cottonindo Ariesta Tbk", sector: "Industrials" },
  { ticker: "LION", name: "Lion Metal Works Tbk", sector: "Industrials" },
  { ticker: "LMSH", name: "Lionmesh Prima Tbk", sector: "Industrials" },
  { ticker: "LPIN", name: "Multi Prima Sejahtera Tbk", sector: "Industrials" },
  { ticker: "MASA", name: "Multistrada Arah Sarana Tbk", sector: "Industrials" },
  { ticker: "MDRN", name: "Modern Internasional Tbk", sector: "Industrials" },
  { ticker: "MFMI", name: "Multifiling Mitra Indonesia Tbk", sector: "Industrials" },
  { ticker: "MKAP", name: "Multikarya Asia Pasifik Raya Tbk", sector: "Industrials" },
  { ticker: "MLPL", name: "Multipolar Tbk", sector: "Industrials" },
  { ticker: "MSJA", name: "Multi Spunindo Jaya Tbk", sector: "Industrials" },
  { ticker: "MUTU", name: "Mutuagung Lestari Tbk", sector: "Industrials" },
  { ticker: "OILS", name: "Indo Oil Perkasa Tbk", sector: "Industrials" },
  { ticker: "PART", name: "Panca Global Prima Tbk", sector: "Industrials" },
  { ticker: "PBSA", name: "Paramita Bangun Sarana Tbk", sector: "Industrials" },
  { ticker: "PGJO", name: "Tourindo Guide Indonesia Tbk", sector: "Industrials" },
  { ticker: "PIPA", name: "Multi Makmur Lemindo Tbk", sector: "Industrials" },
  { ticker: "POLY", name: "Asia Pacific Fibers Tbk", sector: "Industrials" },
  { ticker: "PPRI", name: "Paperocks Indonesia Tbk", sector: "Industrials" },
  { ticker: "PRAS", name: "Prima Alloy Steel Universal Tbk", sector: "Industrials" },
  { ticker: "PTMP", name: "Mitra Pack Tbk", sector: "Industrials" },
  { ticker: "RICY", name: "Ricky Putra Globalindo Tbk", sector: "Industrials" },
  { ticker: "SAGE", name: "Saptausaha Gemilangindah Tbk", sector: "Industrials" },
  { ticker: "SCNP", name: "Selaras Citra Nusantara Perkasa Tbk", sector: "Industrials" },
  { ticker: "SMIL", name: "Sarana Mitra Luas Tbk", sector: "Industrials" },
  { ticker: "SMKM", name: "Sumber Mas Konstruksi Tbk", sector: "Industrials" },
  { ticker: "SOSS", name: "Shield On Service Tbk", sector: "Industrials" },
  { ticker: "SPTO", name: "Surya Pertiwi Tbk", sector: "Industrials" },
  { ticker: "STAR", name: "Buana Artha Anugerah Tbk", sector: "Industrials" },
  { ticker: "SUMI", name: "Sumi Indo Kabel Tbk", sector: "Industrials" },
  { ticker: "TALF", name: "Tunas Alfin Tbk", sector: "Industrials" },
  { ticker: "TFCO", name: "Tifico Fiber Indonesia Tbk", sector: "Industrials" },
  { ticker: "TGUK", name: "Platinum Wahab Nusantara Tbk", sector: "Industrials" },
  { ticker: "UFOE", name: "Damai Sejahtera Abadi Tbk", sector: "Industrials" },
  { ticker: "UNIT", name: "Nusantara Inti Corpora Tbk", sector: "Industrials" },
  { ticker: "UNTR", name: "United Tractors Tbk", sector: "Industrials" },
  { ticker: "VAST", name: "Vastland Indonesia Tbk", sector: "Industrials" },
  { ticker: "VISI", name: "Satu Visi Putra Tbk", sector: "Industrials" },
  { ticker: "VKTR", name: "VKTR Teknologi Mobilitas Tbk", sector: "Industrials" },
  { ticker: "WIDI", name: "Widiant Jaya Krenindo Tbk", sector: "Industrials" },

  // ─── 8. TECHNOLOGY (52 Emiten) ───
  { ticker: "AREA", name: "Dunia Virtual Online Tbk", sector: "Technology" },
  { ticker: "ATIC", name: "Anabatic Technologies Tbk", sector: "Technology" },
  { ticker: "AWAN", name: "Era Digital Media Tbk", sector: "Technology" },
  { ticker: "AXIO", name: "Tera Data Indonusa Tbk", sector: "Technology" },
  { ticker: "BELI", name: "Global Digital Niaga Tbk (Blibli)", sector: "Technology" },
  { ticker: "BUKA", name: "Bukalapak.com Tbk", sector: "Technology" },
  { ticker: "CASH", name: "Cashlez Worldwide Indonesia Tbk", sector: "Technology" },
  { ticker: "CYBR", name: "ITSEC Asia Tbk", sector: "Technology" },
  { ticker: "DATA", name: "Remala Abadi Tbk", sector: "Technology" },
  { ticker: "DCII", name: "DCI Indonesia Tbk", sector: "Technology" },
  { ticker: "DIVA", name: "Distribusi Voucher Nusantara Tbk", sector: "Technology" },
  { ticker: "DMMX", name: "Digital Mediatama Maxima Tbk", sector: "Technology" },
  { ticker: "EDGE", name: "Indointernet Tbk", sector: "Technology" },
  { ticker: "ELIT", name: "Data Sinergitama Jaya Tbk", sector: "Technology" },
  { ticker: "EMTK", name: "Elang Mahkota Teknologi Tbk", sector: "Technology" },
  { ticker: "ENVY", name: "Envy Technologies Indonesia Tbk", sector: "Technology" },
  { ticker: "GLVA", name: "Galva Technologies Tbk", sector: "Technology" },
  { ticker: "GOTO", name: "GoTo Gojek Tokopedia Tbk", sector: "Technology" },
  { ticker: "HDIT", name: "Hensel Davest Indonesia Tbk", sector: "Technology" },
  { ticker: "INFY", name: "Infovesta Utama Tbk", sector: "Technology" },
  { ticker: "INTI", name: "Industri Telekomunikasi Indonesia Tbk", sector: "Technology" },
  { ticker: "IOTF", name: "Sumber Sinergi Makmur Tbk", sector: "Technology" },
  { ticker: "IRSX", name: "Aviana Sinar Abadi Tbk", sector: "Technology" },
  { ticker: "JAST", name: "Jasnita Telekomindo Tbk", sector: "Technology" },
  { ticker: "KIOS", name: "Kioson Komersial Indonesia Tbk", sector: "Technology" },
  { ticker: "LMAX", name: "Limas Indonesia Makmur Tbk", sector: "Technology" },
  { ticker: "LUCK", name: "Sentral Mitra Informatika Tbk", sector: "Technology" },
  { ticker: "MCAS", name: "M Cash Integrasi Tbk", sector: "Technology" },
  { ticker: "METO", name: "Metropolitan Tobacco Tbk", sector: "Technology" },
  { ticker: "MKNT", name: "Mitra Komunikasi Nusantara Tbk", sector: "Technology" },
  { ticker: "MLPT", name: "Multipolar Technology Tbk", sector: "Technology" },
  { ticker: "MTDL", name: "Metrodata Electronics Tbk", sector: "Technology" },
  { ticker: "MULT", name: "Multipolar Technology Tbk", sector: "Technology" },
  { ticker: "NANO", name: "Nanotech Indonesia Global Tbk", sector: "Technology" },
  { ticker: "NFCX", name: "NFC Indonesia Tbk", sector: "Technology" },
  { ticker: "NINE", name: "Techno9 Indonesia Tbk", sector: "Technology" },
  { ticker: "PTSN", name: "Sat Nusapersada Tbk", sector: "Technology" },
  { ticker: "RUNS", name: "Global Sukses Solusi Tbk", sector: "Technology" },
  { ticker: "SKYB", name: "Northcliff Indonesia Tbk", sector: "Technology" },
  { ticker: "TECH", name: "Indosterling Technomedia Tbk", sector: "Technology" },
  { ticker: "TELE", name: "Tiphone Mobile Indonesia Tbk", sector: "Technology" },
  { ticker: "TFAS", name: "Telefast Indonesia Tbk", sector: "Technology" },
  { ticker: "TOSK", name: "Topindo Solusi Komunika Tbk", sector: "Technology" },
  { ticker: "TRG", name: "Trikomsel Oke Tbk", sector: "Technology" },
  { ticker: "TRON", name: "Teknologi Karya Digital Nusa Tbk", sector: "Technology" },
  { ticker: "UKUR", name: "Ukur Sukses Mandiri Tbk", sector: "Technology" },
  { ticker: "UVCR", name: "Trimegah Karya Pratama Tbk", sector: "Technology" },
  { ticker: "WGSH", name: "Wira Global Solusi Tbk", sector: "Technology" },
  { ticker: "WIFI", name: "Solusi Sinergi Digital Tbk", sector: "Technology" },
  { ticker: "WIRG", name: "WIR ASIA Tbk", sector: "Technology" },
  { ticker: "YELO", name: "Yelooo Integra Datanet Tbk", sector: "Technology" },
  { ticker: "ZYRX", name: "Zyrexindo Mandiri Buana Tbk", sector: "Technology" },

  // ─── 9. HEALTHCARE (36 Emiten) ───
  { ticker: "BMHS", name: "Bundamedik Tbk", sector: "Healthcare" },
  { ticker: "CARE", name: "Metro Healthcare Indonesia Tbk", sector: "Healthcare" },
  { ticker: "DGNS", name: "Diagnos Laboratorium Utama Tbk", sector: "Healthcare" },
  { ticker: "DVLA", name: "Darya-Varia Laboratoria Tbk", sector: "Healthcare" },
  { ticker: "HALO", name: "Haloni Jane Tbk", sector: "Healthcare" },
  { ticker: "HEAL", name: "Medikaloka Hermina Tbk", sector: "Healthcare" },
  { ticker: "INAF", name: "Indofarma Tbk", sector: "Healthcare" },
  { ticker: "IRRA", name: "Itama Ranoraya Tbk", sector: "Healthcare" },
  { ticker: "KAEF", name: "Kimia Farma Tbk", sector: "Healthcare" },
  { ticker: "KLBF", name: "Kalbe Farma Tbk", sector: "Healthcare" },
  { ticker: "MEDS", name: "Hetzer Medical Indonesia Tbk", sector: "Healthcare" },
  { ticker: "MERK", name: "Merck Tbk", sector: "Healthcare" },
  { ticker: "MIKA", name: "Mitra Keluarga Karyasehat Tbk", sector: "Healthcare" },
  { ticker: "MMIX", name: "Multi Medika Internasional Tbk", sector: "Healthcare" },
  { ticker: "OBAT", name: "Berkah Mulia Mandiri Tbk", sector: "Healthcare" },
  { ticker: "OBMD", name: "OBM Drilchem Tbk", sector: "Healthcare" },
  { ticker: "OMED", name: "Jayamas Medica Industri Tbk", sector: "Healthcare" },
  { ticker: "PEHA", name: "Phapros Tbk", sector: "Healthcare" },
  { ticker: "PEVE", name: "Penta Valent Tbk", sector: "Healthcare" },
  { ticker: "PRDA", name: "Prodia Widyahusada Tbk", sector: "Healthcare" },
  { ticker: "PRIM", name: "Royal Prima Tbk", sector: "Healthcare" },
  { ticker: "PTLG", name: "Penta Valent Tbk", sector: "Healthcare" },
  { ticker: "PYFA", name: "Pyridam Farma Tbk", sector: "Healthcare" },
  { ticker: "RSCH", name: "Charlie Hospital Semarang Tbk", sector: "Healthcare" },
  { ticker: "RSGK", name: "Kedoya Adyaraya Tbk", sector: "Healthcare" },
  { ticker: "SAME", name: "Sarana Meditama Metropolitan Tbk", sector: "Healthcare" },
  { ticker: "SCPI", name: "Organon Pharma Indonesia Tbk", sector: "Healthcare" },
  { ticker: "SDPC", name: "Millennium Pharmacon International Tbk", sector: "Healthcare" },
  { ticker: "SIDO", name: "Industri Jamu dan Farmasi Sido Muncul Tbk", sector: "Healthcare" },
  { ticker: "SILO", name: "Siloam International Hospitals Tbk", sector: "Healthcare" },
  { ticker: "SOHO", name: "Soho Global Health Tbk", sector: "Healthcare" },
  { ticker: "SRAJ", name: "Sejahteraraya Anugrahjaya Tbk (Mayapada Hospital)", sector: "Healthcare" },
  { ticker: "SURI", name: "Maja Agung Latexindo Tbk", sector: "Healthcare" },
  { ticker: "TAXI", name: "Express Transindo Utama Tbk", sector: "Healthcare" },
  { ticker: "TROY", name: "Maja Agung Latexindo Tbk", sector: "Healthcare" },
  { ticker: "TSPC", name: "Tempo Scan Pacific Tbk", sector: "Healthcare" },

  // ─── 10. PROPERTIES & REAL ESTATE (81 Emiten) ───
  { ticker: "ADCP", name: "Adhi Commuter Properti Tbk", sector: "Properties & Real Estate" },
  { ticker: "AMAN", name: "Makmur Berkah Amanda Tbk", sector: "Properties & Real Estate" },
  { ticker: "APLN", name: "Agung Podomoro Land Tbk", sector: "Properties & Real Estate" },
  { ticker: "ARMY", name: "Armidian Karyatama Tbk", sector: "Properties & Real Estate" },
  { ticker: "ASPI", name: "Andalan Sakti Primaindo Tbk", sector: "Properties & Real Estate" },
  { ticker: "ASRI", name: "Alam Sutera Realty Tbk", sector: "Properties & Real Estate" },
  { ticker: "ATAP", name: "Trimitra Prawara Goldland Tbk", sector: "Properties & Real Estate" },
  { ticker: "BAPA", name: "Bekasi Asri Pemula Tbk", sector: "Properties & Real Estate" },
  { ticker: "BBSS", name: "Bumi Benowo Sukses Sejahtera Tbk", sector: "Properties & Real Estate" },
  { ticker: "BCIP", name: "Bumi Citra Permai Tbk", sector: "Properties & Real Estate" },
  { ticker: "BEST", name: "Bekasi Fajar Industrial Estate Tbk", sector: "Properties & Real Estate" },
  { ticker: "BIKA", name: "Binakarya Jaya Abadi Tbk", sector: "Properties & Real Estate" },
  { ticker: "BKDP", name: "Bukit Darmo Property Tbk", sector: "Properties & Real Estate" },
  { ticker: "BKSL", name: "Sentul City Tbk", sector: "Properties & Real Estate" },
  { ticker: "BLAX", name: "Bliss Properti Indonesia Tbk", sector: "Properties & Real Estate" },
  { ticker: "BSBK", name: "Wulandari Bangun Laksana Tbk", sector: "Properties & Real Estate" },
  { ticker: "BSDE", name: "Bumi Serpong Damai Tbk", sector: "Properties & Real Estate" },
  { ticker: "CBDN", name: "Cahaya Bintang Medan Tbk", sector: "Properties & Real Estate" },
  { ticker: "CITY", name: "Natura City Transportation Tbk", sector: "Properties & Real Estate" },
  { ticker: "COWL", name: "Cowell Development Tbk", sector: "Properties & Real Estate" },
  { ticker: "CTRA", name: "Ciputra Development Tbk", sector: "Properties & Real Estate" },
  { ticker: "DART", name: "Duta Anggada Realty Tbk", sector: "Properties & Real Estate" },
  { ticker: "DILD", name: "Intiland Development Tbk", sector: "Properties & Real Estate" },
  { ticker: "DMAS", name: "Puradelta Lestari Tbk", sector: "Properties & Real Estate" },
  { ticker: "DUTI", name: "Duta Pertiwi Tbk", sector: "Properties & Real Estate" },
  { ticker: "ELTY", name: "Bakrieland Development Tbk", sector: "Properties & Real Estate" },
  { ticker: "EMDE", name: "Megapolitan Developments Tbk", sector: "Properties & Real Estate" },
  { ticker: "FMII", name: "Fortune Mate Indonesia Tbk", sector: "Properties & Real Estate" },
  { ticker: "FORZ", name: "Forza Land Indonesia Tbk", sector: "Properties & Real Estate" },
  { ticker: "GAMA", name: "Aksara Global Media Tbk", sector: "Properties & Real Estate" },
  { ticker: "GMTD", name: "Gowa Makassar Tourism Development Tbk", sector: "Properties & Real Estate" },
  { ticker: "GPRA", name: "Perdana Gapuraprima Tbk", sector: "Properties & Real Estate" },
  { ticker: "GRIA", name: "Ingria Pratama Capitalindo Tbk", sector: "Properties & Real Estate" },
  { ticker: "GWSA", name: "Greenwood Sejahtera Tbk", sector: "Properties & Real Estate" },
  { ticker: "HOMI", name: "Grand House Mulia Tbk", sector: "Properties & Real Estate" },
  { ticker: "JRPT", name: "Jaya Real Property Tbk", sector: "Properties & Real Estate" },
  { ticker: "KENC", name: "Kencana Mulia Pratama Tbk", sector: "Properties & Real Estate" },
  { ticker: "KIJA", name: "Kawasan Industri Jababeka Tbk", sector: "Properties & Real Estate" },
  { ticker: "LAMI", name: "Lamicitra Nusantara Tbk", sector: "Properties & Real Estate" },
  { ticker: "LAND", name: "Trimitra Propertindo Tbk", sector: "Properties & Real Estate" },
  { ticker: "LCGP", name: "Eureka Prima Jakarta Tbk", sector: "Properties & Real Estate" },
  { ticker: "LPCK", name: "Lippo Cikarang Tbk", sector: "Properties & Real Estate" },
  { ticker: "LPKR", name: "Lippo Karawaci Tbk", sector: "Properties & Real Estate" },
  { ticker: "MDLN", name: "Modernland Realty Tbk", sector: "Properties & Real Estate" },
  { ticker: "MKPI", name: "Metropolitan Kentjana Tbk", sector: "Properties & Real Estate" },
  { ticker: "MMLP", name: "Mega Manunggal Property Tbk", sector: "Properties & Real Estate" },
  { ticker: "MPRO", name: "Maha Properti Indonesia Tbk", sector: "Properties & Real Estate" },
  { ticker: "MTLA", name: "Metropolitan Land Tbk", sector: "Properties & Real Estate" },
  { ticker: "MTSM", name: "Metro Realty Tbk", sector: "Properties & Real Estate" },
  { ticker: "MYRX", name: "Hanson International Tbk", sector: "Properties & Real Estate" },
  { ticker: "NATO", name: "Surya Permata Indah Tbk", sector: "Properties & Real Estate" },
  { ticker: "NIRO", name: "City Retail Developments Tbk", sector: "Properties & Real Estate" },
  { ticker: "NZIA", name: "Nusantara Almazia Tbk", sector: "Properties & Real Estate" },
  { ticker: "PAMG", name: "Bima Sakti Pertiwi Tbk", sector: "Properties & Real Estate" },
  { ticker: "PLIN", name: "Plaza Indonesia Realty Tbk", sector: "Properties & Real Estate" },
  { ticker: "POLI", name: "Pollux Investasi Internasional Tbk", sector: "Properties & Real Estate" },
  { ticker: "POLL", name: "Pollux Properties Indonesia Tbk", sector: "Properties & Real Estate" },
  { ticker: "PPRO", name: "PP Properti Tbk", sector: "Properties & Real Estate" },
  { ticker: "PUDP", name: "Pudjiadi Prestige Tbk", sector: "Properties & Real Estate" },
  { ticker: "PURI", name: "Puri Global Sukses Tbk", sector: "Properties & Real Estate" },
  { ticker: "PWON", name: "Pakuwon Jati Tbk", sector: "Properties & Real Estate" },
  { ticker: "RBMS", name: "Ristia Bintang Mahkotasejati Tbk", sector: "Properties & Real Estate" },
  { ticker: "RDTX", name: "Roda Vivatex Tbk", sector: "Properties & Real Estate" },
  { ticker: "REAL", name: "Repower Asia Indonesia Tbk", sector: "Properties & Real Estate" },
  { ticker: "RELF", name: "Graha Mitra Asia Tbk", sector: "Properties & Real Estate" },
  { ticker: "RIMO", name: "Rimo International Lestari Tbk", sector: "Properties & Real Estate" },
  { ticker: "RISE", name: "Jaya Sukses Makmur Sentosa Tbk", sector: "Properties & Real Estate" },
  { ticker: "ROCK", name: "Rockfields Properti Indonesia Tbk", sector: "Properties & Real Estate" },
  { ticker: "RODA", name: "Pikko Land Development Tbk", sector: "Properties & Real Estate" },
  { ticker: "SATU", name: "Kota Satu Properti Tbk", sector: "Properties & Real Estate" },
  { ticker: "SMDM", name: "Suryamas Dutamakmur Tbk", sector: "Properties & Real Estate" },
  { ticker: "SMRA", name: "Summarecon Agung Tbk", sector: "Properties & Real Estate" },
  { ticker: "SSIA", name: "Surya Semesta Internusa Tbk", sector: "Properties & Real Estate" },
  { ticker: "SWID", name: "Saraswanti Indoland Development Tbk", sector: "Properties & Real Estate" },
  { ticker: "TAPA", name: "Padma Alam Tbk", sector: "Properties & Real Estate" },
  { ticker: "TARA", name: "Agung Semesta Sejahtera Tbk", sector: "Properties & Real Estate" },
  { ticker: "TRIN", name: "Perintis Triniti Properti Tbk", sector: "Properties & Real Estate" },
  { ticker: "TRUE", name: "Triniti Dinamik Tbk", sector: "Properties & Real Estate" },
  { ticker: "URBN", name: "Urban Jakarta Propertindo Tbk", sector: "Properties & Real Estate" },
  { ticker: "WINR", name: "Winner Nusantara Jaya Tbk", sector: "Properties & Real Estate" },
  { ticker: "ZONA", name: "Zona Nusantara Investama Tbk", sector: "Properties & Real Estate" },

  // ─── 11. TRANSPORTATION & LOGISTICS (51 Emiten) ───
  { ticker: "ASSA", name: "Adi Sarana Armada Tbk", sector: "Transportation & Logistics" },
  { ticker: "BBRM", name: "Pelayaran Nasional Bina Buana Raya Tbk", sector: "Transportation & Logistics" },
  { ticker: "BIRD", name: "Blue Bird Tbk", sector: "Transportation & Logistics" },
  { ticker: "BLTA", name: "Berlian Laju Tanker Tbk", sector: "Transportation & Logistics" },
  { ticker: "BOAT", name: "Pelayaran Kurnia Lautan Semesta Tbk", sector: "Transportation & Logistics" },
  { ticker: "BULL", name: "Buana Lintas Lautan Tbk", sector: "Transportation & Logistics" },
  { ticker: "CANI", name: "Capitol Nusantara Indonesia Tbk", sector: "Transportation & Logistics" },
  { ticker: "CASS", name: "Cardig Aero Services Tbk", sector: "Transportation & Logistics" },
  { ticker: "CMPP", name: "AirAsia Indonesia Tbk", sector: "Transportation & Logistics" },
  { ticker: "DEAL", name: "Dewata Freightinternational Tbk", sector: "Transportation & Logistics" },
  { ticker: "ELPI", name: "Pelayaran Nasional Ekalya Purnamasari Tbk", sector: "Transportation & Logistics" },
  { ticker: "GIAA", name: "Garuda Indonesia (Persero) Tbk", sector: "Transportation & Logistics" },
  { ticker: "GRPH", name: "Grahaprima Suksesmandiri Tbk", sector: "Transportation & Logistics" },
  { ticker: "GTRA", name: "Grahaprima Suksesmandiri Tbk", sector: "Transportation & Logistics" },
  { ticker: "GTSI", name: "GTS Internasional Tbk", sector: "Transportation & Logistics" },
  { ticker: "HAIS", name: "Hasnur Internasional Shipping Tbk", sector: "Transportation & Logistics" },
  { ticker: "HATM", name: "Habco Trans Maritima Tbk", sector: "Transportation & Logistics" },
  { ticker: "HELI", name: "Jaya Trishindo Tbk", sector: "Transportation & Logistics" },
  { ticker: "HITS", name: "Humpuss Intermoda Transportasi Tbk", sector: "Transportation & Logistics" },
  { ticker: "HUMI", name: "Humpuss Maritim Internasional Tbk", sector: "Transportation & Logistics" },
  { ticker: "IPCC", name: "Indonesia Kendaraan Terminal Tbk", sector: "Transportation & Logistics" },
  { ticker: "IPCM", name: "Jasa Armada Indonesia Tbk", sector: "Transportation & Logistics" },
  { ticker: "JAYA", name: "Armada Berjaya Trans Tbk", sector: "Transportation & Logistics" },
  { ticker: "KARW", name: "ICTSI Jasa Prima Tbk", sector: "Transportation & Logistics" },
  { ticker: "KJEN", name: "Krida Jaringan Nusantara Tbk", sector: "Transportation & Logistics" },
  { ticker: "LOPI", name: "Logisticsplus International Tbk", sector: "Transportation & Logistics" },
  { ticker: "LRNA", name: "Eka Sari Lorena Transport Tbk", sector: "Transportation & Logistics" },
  { ticker: "MIRA", name: "Mitra Rajasa Tbk", sector: "Transportation & Logistics" },
  { ticker: "MPXL", name: "MPX Logistics International Tbk", sector: "Transportation & Logistics" },
  { ticker: "NELY", name: "Pelayaran Nelly Dwi Putri Tbk", sector: "Transportation & Logistics" },
  { ticker: "NUSL", name: "Nusa Lautan Tbk", sector: "Transportation & Logistics" },
  { ticker: "PORT", name: "Nusantara Pelabuhan Handal Tbk", sector: "Transportation & Logistics" },
  { ticker: "PSSI", name: "Pelita Samudera Shipping Tbk", sector: "Transportation & Logistics" },
  { ticker: "PURA", name: "Pura Transportasi Tbk", sector: "Transportation & Logistics" },
  { ticker: "SAFE", name: "Steady Safe Tbk", sector: "Transportation & Logistics" },
  { ticker: "SAPX", name: "Satria Antaran Prima Tbk", sector: "Transportation & Logistics" },
  { ticker: "SDMU", name: "Sidomulyo Selaras Tbk", sector: "Transportation & Logistics" },
  { ticker: "SMDR", name: "Samudera Indonesia Tbk", sector: "Transportation & Logistics" },
  { ticker: "SOCI", name: "Soechi Lines Tbk", sector: "Transportation & Logistics" },
  { ticker: "SOTN", name: "Satria Antaran Prima Tbk", sector: "Transportation & Logistics" },
  { ticker: "TCPI", name: "Transcoal Pacific Tbk", sector: "Transportation & Logistics" },
  { ticker: "TMAS", name: "Temas Tbk", sector: "Transportation & Logistics" },
  { ticker: "TNCA", name: "Trimuda Nuansa Citra Tbk", sector: "Transportation & Logistics" },
  { ticker: "TPMA", name: "Trans Power Marine Tbk", sector: "Transportation & Logistics" },
  { ticker: "TRJA", name: "Transkon Jaya Tbk", sector: "Transportation & Logistics" },
  { ticker: "TRUK", name: "Guna Timur Raya Tbk", sector: "Transportation & Logistics" },
  { ticker: "TSAB", name: "Trans Samudera Bersama Tbk", sector: "Transportation & Logistics" },
  { ticker: "WEHA", name: "WEHA Transportasi Indonesia Tbk", sector: "Transportation & Logistics" },
  { ticker: "WINS", name: "Wintermar Offshore Marine Tbk", sector: "Transportation & Logistics" },
  { ticker: "YASA", name: "Yasa Wahana Tirta Samudera Tbk", sector: "Transportation & Logistics" },
  { ticker: "ZBRA", name: "Dosni Roha Indonesia Tbk", sector: "Transportation & Logistics" },

];

const BLUECHIP_TICKERS = [
  "BBCA",
  "BBRI",
  "BMRI",
  "BBNI",
  "BRIS",
  "BUMI",
  "BDMN",
  "ASII",
  "TLKM",
  "ICBP",
  "INDF",
  "AMRT",
  "AKRA",
  "MEDC",
  "PGAS",
  "KLBF",
  "UNVR",
  "GOTO",
  "ADRO",
  "PTBA",
];
const BLUECHIP_ORDER = new Map(BLUECHIP_TICKERS.map((t, idx) => [t, idx]));

/**
 * Instant client-side search across IDX universe.
 * Prioritizes: Starts with ticker (Bluechips ranked first) -> Contains ticker -> Contains company name.
 * Saat user mengetik "B", saham raksasa (BBCA, BBRI, BMRI, BBNI, BRIS, BUMI, BDMN) langsung menduduki baris teratas.
 * Zero network latency (0ms) and zero API quota consumption.
 */
export function searchIdxTickers(query: string, limit = 8): IdxTickerItem[] {
  if (!query || !query.trim()) return [];
  const q = query.trim().toUpperCase();

  // 1. Prioritas Pertama: Ticker yang DIAWALI dengan query (misal: "B" -> BBCA, BBRI, BMRI, BBNI, BRIS, BUMI, BDMN)
  const startsWithTicker = IDX_UNIVERSE.filter((item) => item.ticker.startsWith(q));

  // Urutkan startsWithTicker: Tempatkan saham raksasa/populer teratas
  startsWithTicker.sort((a, b) => {
    if (a.ticker === q) return -1;
    if (b.ticker === q) return 1;

    const rankA = BLUECHIP_ORDER.has(a.ticker) ? (BLUECHIP_ORDER.get(a.ticker) as number) : 999;
    const rankB = BLUECHIP_ORDER.has(b.ticker) ? (BLUECHIP_ORDER.get(b.ticker) as number) : 999;
    if (rankA !== rankB) return rankA - rankB;
    return a.ticker.localeCompare(b.ticker);
  });

  // 2. Prioritas Kedua: Ticker yang MENGANDUNG query di tengah
  const containsTicker = IDX_UNIVERSE.filter(
    (item) => !item.ticker.startsWith(q) && item.ticker.includes(q)
  );

  // 3. Prioritas Ketiga: Nama perusahaan yang diawali / mengandung query
  const containsName = IDX_UNIVERSE.filter(
    (item) => !item.ticker.includes(q) && item.name.toUpperCase().includes(q)
  );

  // Gabungkan dan potong sesuai limit
  return [...startsWithTicker, ...containsTicker, ...containsName].slice(0, limit);
}

/**
 * Direct O(1) lookup helper by ticker symbol.
 */
const TICKER_MAP = new Map<string, IdxTickerItem>();
for (const item of IDX_UNIVERSE) {
  TICKER_MAP.set(item.ticker, item);
}

export function getIdxTicker(ticker: string): IdxTickerItem | undefined {
  if (!ticker) return undefined;
  return TICKER_MAP.get(ticker.trim().toUpperCase());
}

/**
 * Total active ticker count in this universe dataset.
 */
export const IDX_UNIVERSE_COUNT = IDX_UNIVERSE.length;
